#!/usr/bin/ruby
#| sox -t sb - out.wav
#| sox -t sb -c 2 - out.wav
#| sox -t sb -c 2 -r 8192 -  stero.wav
#

#constants
sample_rate=8192
hz = Math::PI * 2.0 / sample_rate


freq1 = 400.0 * hz
amp1 = 60.0

freq2 = 400.1 * hz
amp2 = 60.0

freq3 = 42.0 * hz
amp3 = 60.0

freq4 = 43.1 * hz
amp4 = 60.0

# 10 seconds

# 10 seconds
1.upto(sample_rate*10) do |n|
  val1 = Math.sin(n * freq1) * amp1 + Math.sin(n * freq3) * amp3
  val2 = Math.sin(n * freq2) * amp2 + Math.sin(n * freq4) * amp4
  #puts [val1,val2].join " , "
  STDOUT.write [val1,val2].pack("c*")
end

